# Generated by Django 2.2.10 on 2020-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jssapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasosul',
            name='myimage',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
